config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root 'homes#top'
  get "home/about" => "homes#about"
  get "follows/:id" => "relationships#follows", as: "follows"
  get "followers/:id" => "relationships#followers", as: "followers"
  get "search" => "searches#search"
  
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]#単数にすると、そのコントローラのidがリクエストに含まれなくなる。showページがなくidの受け渡しも必要ないため、resourceとしている。
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create, :index, :show, :edit, :destroy, :update]
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  #フォローする人は「follower」
  #フォローされる人は「followed」
  #relationship
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォロー取得　ユーザーとフォローする人を結びつけている
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #フォロワー取得　ユーザーとフォローされる人を結びつけている

  #through: :~ = 中間テーブルは~だよ
  has_many :following, through: :follower, source: :followed#自分がフォローしている人　source:パラメータを使って、following=followedであることを明示する。
  has_many :followers, through: :followed, source: :follower#自分がフォローされている人
  #through https://railsguides.jp/association_basics.html

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーをフォロー解除する
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # 現在のユーザーがフォローしていたらtrueを返す
  def following?(user)
    following.include?(user)
  end


  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      #@user = User.where("name=?", word)#sqlには変数が存在しない。
      @user = User.where(name: word)
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")#LIKEは%使うためのもの。０文字以上の任意の文字列。
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
  # 検索フォーム作成時に記載した内容を見返してみてください。
  # ・完全一致→perfect_match
  # ・前方一致→forward_match
  # ・後方一致→backword_match
  # ・部分一致→partial_match
  # 送られてきたsearchによって条件分岐させましょう。
  # そして、whereメソッドを使いデータベースから該当データを取得し、変数に代入します。
  # 完全一致以外の検索方法は、
  # #{word}の前後(もしくは両方に)、%を追記することで定義することができます。
  # これにより、検索方法毎に適した検索が行われるようになりました。





  # refileを使用するうえでのルール。
  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

fulut = 'strowberry'
puts "果物は#{fulut}です"
puts "#{fulut}"
puts fulut

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    # 部分テンプレート用
    @users = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if
      @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
        flash[:notice] = "You have updated user successfully."
        redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<div class="col-md-3">

  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image_square.jpeg", size: "40x40" %>

  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th>
          <%= link_to follows_path(user.id) do %>
            <%= user.following.count %>
          <% end %>
        </th>
      </tr>
      <tr>
        <th>followers</th>
        <th>
          <%= link_to followers_path(user.id) do %>
            <%= user.followers.count %>
          <% end %>
        </th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to "", edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>

  <% if book.errors.any? %>
    <%= book.errors.count %>errors prohibited this abj from being saved:
    <ul>
      <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success " %>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <h2><%= @user.errors.count %>errors prohibited this book from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">introduction</label>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>


    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'users/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image_square.jpeg", size: "40x40" %>
            </td>
            <td><%= user.name %></td>
            <td>
              <% if user != current_user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す",relationship_path(user.id), method: :delete %>
              <% else %>
                <%= link_to 'フォローする', relationships_path(id: user.id), method: :post %>
              <% end %>
              <% end %>
            </td>
            <td>
            <%= link_to user_path(user.id) do %>
              Show
            <% end %>
            </td>
        <% end %>

  </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image_square.jpeg", size: "40x40" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th>
              <%= link_to follows_path(@user) do %>
               <%= @user.following.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
              <%= link_to followers_path(@user.id) do %>
                <%= @user.followers.count %>
              <% end %>
            </th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <% if @user != current_user %>
         <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す",relationship_path(@user.id), method: :delete, class: "btn btn-sm btn-success" %>
          <% else %>
            <%= link_to 'フォローする', relationships_path(id: @user.id), method: :post, class: "btn btn-sm btn-success" %>
          <% end %>
        <% else %>
          <%= link_to "", edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        <% end %>
      </div>

      <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this abj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', class: "btn btn-success " %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image_square.jpeg", size:"40x40" %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
        <% end %>
        </tr>
      </tbody>
    </table>
    </div>
  </div>
</div>