config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root 'homes#top'
  get "home/about" => "homes#about"
  get "follows/:id" => "relationships#follows", as: "follows"
  get "followers/:id" => "relationships#followers", as: "followers"
  get "search" => "searches#search"
  
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]#単数にすると、そのコントローラのidがリクエストに含まれなくなる。showページがなくidの受け渡しも必要ないため、resourceとしている。
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create, :index, :show, :edit, :destroy, :update]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!--<div class="card w-50 mx-auto mt-4 shadow-lg">
  card」classには以降の子要素で使用するclassが依存する形になります。
  その他のclassはサイズ、padding、margin、影を付けるといったcardの構成には関係のないclassです。-->
  <!--(mx-auto)=水平方向にセンタリング-->
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <span>
            <%= link_to "Bookers", root_path, class: "navbar-brand" %>
          </span>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
                  </li>
                <li>
                  <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
                </li>
                <li>
                  <%=link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="row">
            <% if user_signed_in? %>
              <div class="col-xs-6 col-xs-offset-3 text-center mx-auto" style="margin-top: 25px;">
                <%= form_with url: search_path, local: true, method: :get do |f| %><!--url: search_path = 検索内容を、作成したルーティングに送信します。-->
                  <%= f.text_field :word %><!--検索内容をwordとしてアクションに送っている-->
                  <%= f.select :range, options_for_select([['User'], ['Book']]) %><!--UsermoモデルとBookモデルを選択できるようにしている。洗濯したモデルをrangeとしてアクションに送っている-->
                  <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致", "backword_match"], ["部分一致","partial_match"]]) %>
                  <%= f.submit "検索", class: "btn btn-primary" %>
                  <!--↑検索手法を定義している。選択した検索手法をsearchとしてアクションに送っている-->
                <% end %>
              </div>
            <% end %>
          </div>
    </header>
    <main>
      <p id="notice"><%= flash[:notice] %></p>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5"> <!-- mt = margintop or padding-top -->
        <div class="row">
          <div class="mx-auto"><!-- mx-auto = 固定幅のブロックレベルのコンテンツを水平にセンタリングする -->
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>